version: '3'
services:
  bff:
    build: ./bff
    ports:
      - "3000:3000"
    depends_on:
      - mf_drawer
      - mf_videos

  mf_drawer:
    build: ./mf_drawer
    ports:
      - "3001:3001"

  mf_videos:
    build: ./mf_videos
    ports:
      - "3002:3002"
